# Generated by Django 5.2.5 on 2025-08-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idetudiant', models.AutoField(db_column='IDEtudiant', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=100)),
                ('prenom', models.CharField(db_column='Prenom', max_length=100)),
                ('nomarabe', models.CharField(blank=True, db_column='NomArabe', max_length=100, null=True)),
                ('prenomarabe', models.CharField(blank=True, db_column='PrenomArabe', max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, db_column='Sexe', max_length=10, null=True)),
                ('datenaissance', models.DateField(blank=True, db_column='DateNaissance', null=True)),
                ('lieunaissance', models.CharField(blank=True, db_column='LieuNaissance', max_length=100, null=True)),
                ('nationalite', models.CharField(blank=True, db_column='Nationalite', max_length=50, null=True)),
                ('nin', models.CharField(blank=True, db_column='NIN', max_length=50, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, db_column='Adresse', null=True)),
                ('telephone', models.CharField(blank=True, db_column='Telephone', max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True, unique=True)),
                ('niveauetude', models.CharField(blank=True, db_column='NiveauEtude', max_length=100, null=True)),
                ('dernierdiplome', models.CharField(blank=True, db_column='DernierDiplome', max_length=100, null=True)),
                ('situationprofessionnelle', models.CharField(blank=True, db_column='SituationProfessionnelle', max_length=100, null=True)),
                ('photo', models.CharField(blank=True, db_column='Photo', max_length=255, null=True)),
                ('dateinscription', models.DateField(blank=True, db_column='DateInscription', null=True)),
                ('idformation', models.IntegerField(blank=True, db_column='IDFormation', null=True)),
                ('dureeformation', models.CharField(blank=True, db_column='DureeFormation', max_length=50, null=True)),
                ('salle', models.CharField(blank=True, db_column='Salle', max_length=50, null=True)),
                ('formation', models.CharField(blank=True, db_column='Formation', max_length=100, null=True)),
                ('idsalle', models.IntegerField(blank=True, db_column='IDSalle', null=True)),
                ('statut', models.CharField(blank=True, db_column='Statut', max_length=50, null=True)),
                ('remarques', models.TextField(blank=True, db_column='Remarques', null=True)),
            ],
            options={
                'db_table': 'etudiant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('idutilisateurs', models.AutoField(db_column='IDUtilisateurs', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=100)),
                ('prenom', models.CharField(db_column='Prenom', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=150, unique=True)),
                ('mp', models.CharField(db_column='MP', max_length=255)),
                ('statut', models.CharField(blank=True, db_column='Statut', max_length=50, null=True)),
                ('photo', models.CharField(blank=True, db_column='Photo', max_length=255, null=True)),
                ('etat_compte', models.CharField(blank=True, db_column='Etat_compte', max_length=50, null=True)),
                ('date_creation', models.DateTimeField(blank=True, db_column='Date_creation', null=True)),
                ('dernier_connexion', models.DateTimeField(blank=True, db_column='Dernier_connexion', null=True)),
                ('code_utilisateurs', models.CharField(blank=True, db_column='Code_Utilisateurs', max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'managed': True,
            },
        ),
    ]
