# Generated by Django 5.2.5 on 2025-08-16 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityFormateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.SmallIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'availability_formateur',
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_import', models.DateTimeField(blank=True, null=True)),
                ('bank_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('matched', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('notifications_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar_event',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(blank=True, max_length=100, null=True)),
                ('fichier_certificat', models.CharField(blank=True, max_length=512, null=True)),
                ('date_delivrance', models.DateTimeField(blank=True, null=True)),
                ('valide_jusqua', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_etudiant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_fonctionnaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree', models.CharField(blank=True, max_length=50, null=True)),
                ('branche', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'formation',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(default='inscrit', max_length=50)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inscription',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_emission', models.DateTimeField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='emi', max_length=50)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('duree', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('formation', models.ForeignKey(db_column='formation_id', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Schoolapp.formation')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paiement',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_plan',
            },
        ),
        migrations.CreateModel(
            name='ProgressionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complet', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'progression_module',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('equipements', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'salle',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('horaire_debut', models.TimeField(blank=True, null=True)),
                ('horaire_fin', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('formation', models.ForeignKey(db_column='formation_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Schoolapp.formation')),
                ('salle', models.ForeignKey(blank=True, db_column='salle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Schoolapp.salle')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(default='document', max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('formation', models.ForeignKey(blank=True, db_column='formation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports', to='Schoolapp.formation')),
                ('module', models.ForeignKey(blank=True, db_column='module_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports', to='Schoolapp.module')),
            ],
            options={
                'db_table': 'support',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('etat_compte', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('code_utilisateur', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.DeleteModel(
            name='Utilisateurs',
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={},
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='dateinscription',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='datenaissance',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='dernierdiplome',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='dureeformation',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='idetudiant',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='idformation',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='idsalle',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='lieunaissance',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='niveauetude',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='nomarabe',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenomarabe',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='situationprofessionnelle',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='dernier_diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='duree_formation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='formation_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom_arabe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom_arabe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='situation_professionnelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='salle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='formation',
            field=models.ForeignKey(blank=True, db_column='formation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='Schoolapp.formation'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='formation',
            field=models.ForeignKey(blank=True, db_column='formation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='Schoolapp.formation'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(db_column='etudiant_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='Schoolapp.etudiant'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='formation',
            field=models.ForeignKey(db_column='formation_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='Schoolapp.formation'),
        ),
        migrations.AddField(
            model_name='certification',
            name='inscription',
            field=models.ForeignKey(db_column='inscription_id', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='Schoolapp.inscription'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inscription',
            field=models.ForeignKey(blank=True, db_column='inscription_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Schoolapp.inscription'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='etudiant',
            field=models.ForeignKey(db_column='etudiant_id', on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Schoolapp.etudiant'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='formation',
            field=models.ForeignKey(db_column='formation_id', on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Schoolapp.formation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paiement',
            field=models.ForeignKey(blank=True, db_column='paiement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Schoolapp.paiement'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='paiement',
            field=models.ForeignKey(blank=True, db_column='paiement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='Schoolapp.paiement'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='inscription',
            field=models.ForeignKey(db_column='inscription_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='Schoolapp.inscription'),
        ),
        migrations.AddField(
            model_name='progressionmodule',
            name='inscription',
            field=models.ForeignKey(db_column='inscription_id', on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='Schoolapp.inscription'),
        ),
        migrations.AddField(
            model_name='progressionmodule',
            name='module',
            field=models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='Schoolapp.module'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='salle',
            field=models.ForeignKey(blank=True, db_column='salle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='Schoolapp.salle'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='session',
            field=models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='Schoolapp.session'),
        ),
        migrations.AddField(
            model_name='support',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='Schoolapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='session',
            name='formateur',
            field=models.ForeignKey(blank=True, db_column='formateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Schoolapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='certification',
            name='delivre_par',
            field=models.ForeignKey(blank=True, db_column='delivre_par', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifs_delivres', to='Schoolapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='organisateur',
            field=models.ForeignKey(blank=True, db_column='organisateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='Schoolapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='availabilityformateur',
            name='utilisateur',
            field=models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Schoolapp.utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'formation')},
        ),
        migrations.AlterUniqueTogether(
            name='progressionmodule',
            unique_together={('inscription', 'module')},
        ),
    ]
