# Generated by assistant to rename orphaned column
from django.db import migrations


SQL_RENAME = """
ALTER TABLE `etudiant` CHANGE COLUMN `ormation_text` `formation_text` varchar(255) NULL;
"""

SQL_REVERSE = """
ALTER TABLE `etudiant` CHANGE COLUMN `formation_text` `ormation_text` varchar(255) NULL;
"""


class Migration(migrations.Migration):
    dependencies = [
        ('Schoolapp', '0002_availabilityformateur_bankreconciliation_and_more'),
    ]

    operations = [
        migrations.RunSQL(SQL_RENAME, SQL_REVERSE),
    ]
