# Generated by Django 5.2.5 on 2025-09-19 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0005_fournisseurs_and_achats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='description',
            new_name='contenu',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='niveau',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='carte_identite_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='extrait_naissance_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='verification_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formation',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='groupe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='compte_bancaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_cheque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='inscription',
            field=models.ForeignKey(blank=True, db_column='inscription_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='Schoolapp.inscription'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_cheque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='date_achat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='achat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='achatitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='formation',
            field=models.ForeignKey(blank=True, db_column='formation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='Schoolapp.formation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reglementfournisseur',
            name='date_reglement',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reglementfournisseur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(db_column='id_charge', primary_key=True, serialize=False)),
                ('type_charge', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('formation', models.ForeignKey(blank=True, db_column='formation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='Schoolapp.formation')),
            ],
            options={
                'db_table': 'charges',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard')], default='present', max_length=10)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('calendar_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Schoolapp.calendarevent')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Schoolapp.etudiant')),
            ],
            options={
                'db_table': 'presence',
                'unique_together': {('etudiant', 'calendar_event')},
            },
        ),
        migrations.CreateModel(
            name='ReglementEnseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_reglement', models.DateField()),
                ('mode_reglement', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(db_column='enseignant_id', on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='Schoolapp.enseignant')),
            ],
            options={
                'db_table': 'reglement_enseignants',
                'indexes': [models.Index(fields=['enseignant'], name='idx_reglement_enseignant')],
            },
        ),
    ]
