# Generated by Django 5.2.5 on 2025-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0006_rename_description_formation_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='formateur_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='formation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
