# Generated by assistant to add 'groupe' field to CalendarEvent
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0007_calendarevent_formateur_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='groupe',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
