# Generated by Django 6.0 on 2025-12-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0008_add_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'db_table': 'groupe',
            },
        ),
        migrations.CreateModel(
            name='SchoolVersement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecole', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_versement', models.DateField()),
                ('batch_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_versement',
            },
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='organisateur',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='session',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='formation_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='organisateur_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='salle_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='session_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='charges_attachments/'),
        ),
        migrations.AddField(
            model_name='charge',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='ecole',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='ecole',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_datetime'], name='idx_event_start'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['salle_id'], name='idx_event_salle'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['formation_id'], name='idx_event_formation'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['session_id'], name='fk_event_session'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['organisateur_id'], name='fk_event_organisateur'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='formation',
            field=models.ForeignKey(blank=True, db_column='formation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='Schoolapp.formation'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(blank=True, db_column='groupe_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='Schoolapp.groupe'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='groupe',
            field=models.ForeignKey(blank=True, db_column='groupe_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='Schoolapp.groupe'),
        ),
        migrations.AlterUniqueTogether(
            name='groupe',
            unique_together={('nom', 'formation')},
        ),
    ]
