"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e$0gm@=typ4-$_xaz%_(p(yjehdfuzzydb*da2=kve71@c(!fr'

# SECURITY WARNING: don't run with debug turned on in production!
# By default DEBUG is False for production-like behavior. When developing
# locally we want the dev server to serve static/media and use the
# included sqlite database if present. Detect a local sqlite file and
# enable a safe development fallback.

# Default (production-like)
DEBUG = False

# Local development fallback: if a sqlite DB file exists in the project
# root (created for quick local testing), enable DEBUG and switch the
# DATABASES setting to use it. This keeps the change minimal and easy
# to revert for production.
if (BASE_DIR / 'db.sqlite3').exists() or os.environ.get('DEV') == '1':
    DEBUG = True


ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.36', '*']

# CSRF trusted origins for Railway
CSRF_TRUSTED_ORIGINS = [
    'https://genieschool.up.railway.app',
    'https://*.railway.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Schoolapp.apps.SchoolappConfig',
]

MIDDLEWARE = [
    'Schoolapp.cors_middleware.CORSMiddleware',  # <-- AJOUTER CETTE LIGNE
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # ActiveDBMiddleware sets per-request DB alias (reads session/cookie)
    'Schoolapp.middleware.ActiveDBMiddleware',
    'Schoolapp.db_error_middleware.DatabaseErrorMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Schoolapp' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Schoolapp.context_processors.current_user',
                'django.template.context_processors.media',
            ],
        },
    },
]


WSGI_APPLICATION = 'school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Detect if running on Railway
ON_RAILWAY = os.environ.get('RAILWAY_ENVIRONMENT_NAME') is not None

# Primary database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bd_gss_2025',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': 3306,
        'CONN_MAX_AGE': 600,  # Connection pooling
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,
            'read_timeout': 30,
            'write_timeout': 30,
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}



# Log database configuration for debugging
print(f"[SETTINGS] Running on Railway: {ON_RAILWAY}", flush=True)
print(f"[SETTINGS] Configured database: {DATABASES['default'].get('NAME')}@{DATABASES['default'].get('HOST')}:{DATABASES['default'].get('PORT')}", flush=True)

# Disable all middleware that accesses the database at import time
# They should only access DB during request processing
INITIALIZED_AT_STARTUP = True
print(f"[SETTINGS] Django settings loaded successfully. DEBUG={DEBUG}", flush=True)


# Additional database (same credentials, different NAME) so the app can connect
# to an alternate database instance. Use Django's DATABASES setting to reference
# it as 'schooloctobre'. Switching at runtime requires either a DB router or
# views that explicitly use django.db.connections['schooloctobre'].
# Only configure if environment variables are provided
if os.environ.get('SECONDARY_DB_HOST'):
    DATABASES['schooloctobre'] = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('SECONDARY_DB_NAME', 'bdlangue'),      
        'USER': os.environ.get('SECONDARY_DB_USER', 'root'),
        'PASSWORD': os.environ.get('SECONDARY_DB_PASSWORD', ''),
        'HOST': os.environ.get('SECONDARY_DB_HOST'),
        'PORT': int(os.environ.get('SECONDARY_DB_PORT', '3306')),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,
            'read_timeout': 30,
            'write_timeout': 30,
        },
    }
    print(f"[SETTINGS] Secondary database configured: {DATABASES['schooloctobre'].get('NAME')}@{DATABASES['schooloctobre'].get('HOST')}", flush=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use WhiteNoise for static file serving in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use our simple DB router which reads the per-request active DB alias
DATABASE_ROUTERS = ['Schoolapp.dbrouters.SessionDBRouter']


# Email configuration

# Using Gmail SMTP as the default example. If you use a different provider,
# replace EMAIL_HOST/EMAIL_PORT and security settings accordingly.
# Default: use SMTP in production, but when DEBUG=True use console backend for local testing
# To force real SMTP in development set environment variable FORCE_SMTP=1
FORCE_SMTP = os.environ.get('FORCE_SMTP') == '1'
if DEBUG and not FORCE_SMTP:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')

# The account used to authenticate with the SMTP server
# Read credentials from environment variables when possible to avoid
# committing secrets in the repository.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'geniesysteme.school@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Default from address used by send_mail when DEFAULT_FROM_EMAIL is not provided
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Server email (used for error emails) — keep same as default from
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Backwards-compatible alias (some older code may reference EMAIL_FROM)
EMAIL_FROM = DEFAULT_FROM_EMAIL

PASSWORD_RESET_TIMEOUT = 3600  # 1 heure en secondes


# Comprehensive logging configuration for production debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'app.log'),
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'Schoolapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'DEBUG',
    },
}
